// Market data - 10 initial markets
export const markets = [
  {
    id: "kospi-2700",
    title: "코스피가 이번 달 안에 2,700선을 돌파할까?",
    category: "economy",
    categoryLabel: "경제",
    emoji: "📈",
    yesProb: 62,
    noProb: 38,
    yesAmount: 31200,
    noAmount: 19100,
    totalVolume: 50300,
    participants: 1847,
    endDate: "2026-04-30",
    daysLeft: 13,
    description: "코스피 지수가 2026년 4월 말 기준 2,700포인트를 장중 또는 종가 기준으로 돌파하면 YES, 그렇지 않으면 NO.",
    hot: true,
    new: false,
    myBet: null as "yes" | "no" | null,
  },
  {
    id: "usd-krw-1450",
    title: "달러/원 환율이 1,450원 이하로 내려올까?",
    category: "economy",
    categoryLabel: "경제",
    emoji: "💵",
    yesProb: 37,
    noProb: 63,
    yesAmount: 18900,
    noAmount: 32100,
    totalVolume: 51000,
    participants: 2103,
    endDate: "2026-05-15",
    daysLeft: 28,
    description: "원/달러 환율이 2026년 5월 15일 기준으로 1,450원 이하로 내려가면 YES.",
    hot: true,
    new: false,
    myBet: null as "yes" | "no" | null,
  },
  {
    id: "boi-rate-freeze",
    title: "한국은행, 5월 금통위에서 기준금리 동결할까?",
    category: "economy",
    categoryLabel: "경제",
    emoji: "🏦",
    yesProb: 78,
    noProb: 22,
    yesAmount: 42100,
    noAmount: 11900,
    totalVolume: 54000,
    participants: 3201,
    endDate: "2026-05-29",
    daysLeft: 42,
    description: "한국은행 금융통화위원회가 2026년 5월 정례회의에서 기준금리를 동결(현행 유지)하면 YES.",
    hot: false,
    new: false,
    myBet: null as "yes" | "no" | null,
  },
  {
    id: "samsung-80k",
    title: "삼성전자 주가가 한 달 내 8만 원 회복할까?",
    category: "economy",
    categoryLabel: "경제",
    emoji: "📱",
    yesProb: 44,
    noProb: 56,
    yesAmount: 22400,
    noAmount: 28500,
    totalVolume: 50900,
    participants: 2890,
    endDate: "2026-05-16",
    daysLeft: 29,
    description: "삼성전자 보통주 주가가 2026년 5월 16일 기준 종가 8만 원 이상이면 YES.",
    hot: false,
    new: true,
    myBet: null as "yes" | "no" | null,
  },
  {
    id: "opposition-win",
    title: "다음 대선에서 야권 단일 후보가 승리할까?",
    category: "politics",
    categoryLabel: "정치",
    emoji: "🗳️",
    yesProb: 53,
    noProb: 47,
    yesAmount: 28100,
    noAmount: 24900,
    totalVolume: 53000,
    participants: 4512,
    endDate: "2027-03-03",
    daysLeft: 320,
    description: "2027년 대선에서 야권 단일 후보가 최종 당선되면 YES.",
    hot: true,
    new: false,
    myBet: null as "yes" | "no" | null,
  },
  {
    id: "approval-40",
    title: "대통령 지지율이 이달 40%대를 유지할까?",
    category: "politics",
    categoryLabel: "정치",
    emoji: "📊",
    yesProb: 31,
    noProb: 69,
    yesAmount: 15700,
    noAmount: 35200,
    totalVolume: 50900,
    participants: 1983,
    endDate: "2026-04-30",
    daysLeft: 13,
    description: "4월 마지막 주 발표되는 주요 여론조사(갤럽/리얼미터)에서 대통령 지지율이 40~49%이면 YES.",
    hot: false,
    new: false,
    myBet: null as "yes" | "no" | null,
  },
  {
    id: "ko-apartments-rise",
    title: "서울 아파트 평균 매매가 올해 더 오를까?",
    category: "economy",
    categoryLabel: "경제",
    emoji: "🏢",
    yesProb: 58,
    noProb: 42,
    yesAmount: 29800,
    noAmount: 21600,
    totalVolume: 51400,
    participants: 3344,
    endDate: "2026-12-31",
    daysLeft: 258,
    description: "KB국민은행 주택가격동향 기준, 서울 아파트 평균 매매가가 2026년 12월에 1월 대비 상승이면 YES.",
    hot: false,
    new: true,
    myBet: null as "yes" | "no" | null,
  },
  {
    id: "kpop-chart-1",
    title: "BTS 신보, 빌보드 앨범 차트 1위 달성할까?",
    category: "society",
    categoryLabel: "사회/트렌드",
    emoji: "🎵",
    yesProb: 85,
    noProb: 15,
    yesAmount: 45700,
    noAmount: 8100,
    totalVolume: 53800,
    participants: 5821,
    endDate: "2026-06-30",
    daysLeft: 74,
    description: "2026년 내 발매 예정인 BTS 신보가 빌보드 200 차트 1위를 달성하면 YES.",
    hot: true,
    new: false,
    myBet: null as "yes" | "no" | null,
  },
  {
    id: "kdrama-rating-20",
    title: "올해 드라마 중 시청률 20%를 넘는 작품이 나올까?",
    category: "society",
    categoryLabel: "사회/트렌드",
    emoji: "📺",
    yesProb: 49,
    noProb: 51,
    yesAmount: 24900,
    noAmount: 25800,
    totalVolume: 50700,
    participants: 2177,
    endDate: "2026-12-31",
    daysLeft: 258,
    description: "2026년 한국 지상파/케이블 드라마 중 닐슨 코리아 기준 20%를 넘는 에피소드가 나오면 YES.",
    hot: false,
    new: false,
    myBet: null as "yes" | "no" | null,
  },
  {
    id: "national-assembly-bill",
    title: "전국민 지원금 법안, 올해 국회 본회의 통과할까?",
    category: "politics",
    categoryLabel: "정치",
    emoji: "📜",
    yesProb: 23,
    noProb: 77,
    yesAmount: 11800,
    noAmount: 39500,
    totalVolume: 51300,
    participants: 2654,
    endDate: "2026-12-31",
    daysLeft: 258,
    description: "전국민 재난지원금 또는 기본소득 관련 법안이 2026년 안에 국회 본회의를 통과하면 YES.",
    hot: false,
    new: true,
    myBet: null as "yes" | "no" | null,
  },
];

export const leaderboard = [
  { rank: 1, name: "전설의고양이", tier: "oracle", points: 128400, accuracy: 79.3, streak: 12, emoji: "👑" },
  { rank: 2, name: "경제달인김씨", tier: "oracle", points: 98700, accuracy: 74.1, streak: 7, emoji: "🔮" },
  { rank: 3, name: "판세읽는자", tier: "strategist", points: 76300, accuracy: 71.8, streak: 5, emoji: "🧠" },
  { rank: 4, name: "뇨앙군", tier: "strategist", points: 61200, accuracy: 69.5, streak: 3, emoji: "📊" },
  { rank: 5, name: "정치고수", tier: "strategist", points: 53800, accuracy: 67.2, streak: 4, emoji: "📈" },
  { rank: 6, name: "코스피박사", tier: "analyst", points: 44100, accuracy: 65.0, streak: 2, emoji: "💹" },
  { rank: 7, name: "나는야예측왕", tier: "analyst", points: 38700, accuracy: 63.7, streak: 0, emoji: "🎯" },
  { rank: 8, name: "환율여왕", tier: "analyst", points: 32100, accuracy: 62.3, streak: 1, emoji: "💵" },
  { rank: 9, name: "마켓마스터", tier: "predictor", points: 24500, accuracy: 58.9, streak: 3, emoji: "🏆" },
  { rank: 10, name: "신입예측가", tier: "predictor", points: 18900, accuracy: 57.1, streak: 0, emoji: "⭐" },
];

export const tierConfig = {
  rookie: { label: "루키", color: "#94a3b8", minPoints: 0, emoji: "🐣" },
  predictor: { label: "예측가", color: "#22d3a0", minPoints: 100, emoji: "🔮" },
  analyst: { label: "분석가", color: "#60a5fa", minPoints: 500, emoji: "📊" },
  strategist: { label: "전략가", color: "#c084fc", minPoints: 2000, emoji: "🧠" },
  oracle: { label: "오라클", color: "#f59e0b", minPoints: 5000, emoji: "👑" },
};

export function getTier(points: number) {
  if (points >= 5000) return "oracle";
  if (points >= 2000) return "strategist";
  if (points >= 500) return "analyst";
  if (points >= 100) return "predictor";
  return "rookie";
}

export function formatPoints(n: number) {
  if (n >= 10000) return `${(n / 10000).toFixed(1)}만P`;
  return `${n.toLocaleString()}P`;
}

export function formatDate(dateStr: string) {
  const d = new Date(dateStr);
  return `${d.getFullYear()}.${String(d.getMonth() + 1).padStart(2, "0")}.${String(d.getDate()).padStart(2, "0")}`;
}
